
// eslint-disable-next-line @typescript-eslint/no-unused-expressions
response: [
    {
        query_id: 309,
        query: "Visualize the average feedback rating of users based on per campaign objective.",
        response_text: "Here are the average feedback ratings of users for each campaign objective:\n*   **Brand Awareness** campaigns currently have the highest average feedback rating at **3.5**.\n*   **Traffic Growth** campaigns follow closely with an average feedback rating of **3.25**.\n*   **Lead Generation** campaigns show an average feedback rating of **2.58**.\n*   **User Engagement** campaigns have an average feedback rating of **2.55**.\n**In summary,** these results indicate that campaigns focused on Brand Awareness and Traffic Growth are receiving more positive user feedback compared to those centered on Lead Generation and User Engagement. This insight can be valuable for strategically planning and optimizing future campaign efforts.",
        created_at: "2025-11-16T15:25:00.054765Z"
    },
    {
        query_id: 308,
        query: "Display how many vehicles are currently in each status (active, maintenance, inactive).",
        response_text: "Based on your inquiry regarding the current status of vehicles, here is a breakdown of the numbers:\n*   There are **49** vehicles currently in 'active' status.\n*   **49** vehicles are marked as 'inactive'.\n*   And **43** vehicles are currently in 'maintenance' status.\nIn summary, we have an equal number of active and inactive vehicles, totaling 49 each, with 43 vehicles presently undergoing maintenance.",
        created_at: "2025-11-16T15:24:31.083915Z"
    },
    {
        query_id: 307,
        query: "Visualize the total revenue generated on trips per driver.",
        response_text: "Here's a breakdown of the total revenue generated on trips per driver, which should help you visualize performance:\nWe can see a clear range in revenue contributions from our drivers.\n**Top Performers:**\n*   **Matthew Gardner** leads with a total revenue of **39106.77**.\n*   **Stephanie Shaw** follows closely with **34981.07**.\n*   **Steven Richards** is also a strong contributor, generating **33697.56**.\n**General Overview:**\nThe revenue generated by drivers varies significantly, ranging from high earners like Matthew Gardner to others with lower totals such as Natalie Palmer, who generated **860.54**. This data provides a comprehensive view of individual driver performance and their direct impact on trip revenue.\n**Insights:**\nThis information is highly valuable for understanding individual driver contributions. You can use these figures to:\n*   Identify top-performing drivers who are generating the most revenue.\n*   Analyze the distribution of revenue across your driver base.\n*   Potentially identify areas for performance improvement or incentive programs.",
        created_at: "2025-11-16T15:22:41.450689Z"
    },
    {
        query_id: 306,
        query: "Show trend of total revenue (net amount) generated each month.",
        response_text: "Here is the trend of your total net revenue generated each month:\n*   **May 2025:** The month started with a total revenue of 131384.28.\n*   **June 2025:** Revenue saw an increase, reaching 189623.42.\n*   **July 2025:** There was a dip in revenue, settling at 143361.08.\n*   **August 2025:** This month marked the highest performance, with total revenue peaking at 221590.25.\n*   **September 2025:** Revenue experienced a slight decrease to 212674.56.\n*   **October 2025:** The downward trend continued, with revenue at 198500.11.\n*   **November 2025:** We observed a significant decline, with revenue dropping to 67086.81, which is the lowest for this period.\n**Summary of the Trend:**\nOverall, the revenue trend shows an initial increase leading to a peak in August 2025. Following this peak, there's a clear downward trajectory from September to November 2025, with November recording the lowest revenue figure for the given period. This suggests a strong performance in mid-year which then tapered off significantly towards the end of the provided period.",
        created_at: "2025-11-16T14:21:36.651302Z"
    },
    {
        query_id: 305,
        query: "Plot the number of accidents recorded each month this year.",
        response_text: "Certainly, here is the breakdown of the number of accidents recorded each month this year, as per your request to plot this data:\n*   **January:** 5 accidents\n*   **February:** 8 accidents\n*   **March:** 3 accidents\n*   **April:** 3 accidents\n*   **May:** 6 accidents\n*   **June:** 3 accidents\n*   **July:** 4 accidents\n*   **August:** 3 accidents\n*   **September:** 7 accidents\n*   **October:** 6 accidents\n*   **November:** 1 accident\n**Key Insights:**\nFrom this data, we can observe that **February recorded the highest number of accidents with 8 incidents**, followed by September with 7 accidents. Conversely, **November reported the lowest number of accidents, with only 1 incident**. There were also periods of consistently lower accident numbers, specifically in March, April, June, and August, each recording 3 accidents. This provides a clear overview of monthly accident trends for the current year.",
        created_at: "2025-11-16T14:07:34.753898Z"
    }
]
