export const dataSources = [
    {
        id: "sqlserver",
        color: "bg-primary/20 text-primary",
        title: "SQL Server",
        desc: "Microsoft SQL Server database connection",
        icon: "fa-database",
        img: "/sql_server.svg",
    },
    {
        id: "mysql",
        color: "bg-blue-900/30 text-blue-400",
        title: "mySQL",
        desc: "MySQL database connection",
        icon: "fa-server",
        img: "/Mysql.svg",
    },
    {
        id: "postgresql",
        color: "bg-indigo-900/30 text-indigo-400",
        title: "PostgreSQL",
        desc: "PostgreSQL database connection",
        icon: "fa-database",
        img: "/postgres.svg",
    },
    {
        id: "oracle",
        color: "bg-red-900/30 text-red-400",
        title: "Oracle",
        desc: "Oracle database connection",
        icon: "fa-circle-nodes",
        img: "/Oracle.svg",
    },
    {
        id: "mongodb",
        color: "bg-green-900/30 text-green-400",
        title: "mongoDB",
        desc: "NoSQL MongoDB connection",
        icon: "fa-leaf",
        img: "/Mongodb.svg",
    },
    {
        id: "snowflake",
        color: "bg-cyan-900/30 text-cyan-400",
        title: "Snowflake",
        desc: "Snowflake data warehouse connection",
        icon: "fa-snowflake",
        img: "/Snowflake.svg",
    },
    {
        id: "redshift",
        color: "bg-orange-900/30 text-orange-400",
        title: "Amazon Redshift",
        desc: "AWS Redshift database connection",
        icon: "fa-aws",
        img: "/RedShift.svg",
    },
    {
        id: "bigquery",
        color: "bg-cyan-900/30 text-cyan-400",
        title: "Google BigQuery",
        desc: "Google Cloud data warehouse",
        icon: "fa-google",
        img: "/GoogleBigQuery.svg",
    },
    {
        id: "azure",
        color: "bg-cyan-900/30 text-cyan-400",
        title: "Azure SQL",
        desc: "Microsoft Azure SQL database",
        icon: "fa-microsoft",
        img: "/Azure.svg",
    },
];


export const dataSourcesByTitle: Record<string, any> = {
    "SQL Server": {
        id: "sqlserver",
        color: "bg-primary/20 text-primary",
        title: "SQL Server",
        desc: "Microsoft SQL Server database connection",
        icon: "fa-database",
        img: "/sql_server.svg",
    },
    mySQL: {
        id: "mysql",
        color: "bg-blue-900/30 text-blue-400",
        title: "mySQL",
        desc: "MySQL database connection",
        icon: "fa-server",
        img: "/Mysql.svg",
    },
    PostgreSQL: {
        id: "postgresql",
        color: "bg-indigo-900/30 text-indigo-400",
        title: "PostgreSQL",
        desc: "PostgreSQL database connection",
        icon: "fa-database",
        img: "/postgres.svg",
    },
    Oracle: {
        id: "oracle",
        color: "bg-red-900/30 text-red-400",
        title: "Oracle",
        desc: "Oracle database connection",
        icon: "fa-circle-nodes",
        img: "/Oracle.svg",
    },
    mongoDB: {
        id: "mongodb",
        color: "bg-green-900/30 text-green-400",
        title: "mongoDB",
        desc: "NoSQL MongoDB connection",
        icon: "fa-leaf",
        img: "/Mongodb.svg",
    },
    Snowflake: {
        id: "snowflake",
        color: "bg-cyan-900/30 text-cyan-400",
        title: "Snowflake",
        desc: "Snowflake data warehouse connection",
        icon: "fa-snowflake",
        img: "/Snowflake.svg",
    },
    "Amazon Redshift": {
        id: "redshift",
        color: "bg-orange-900/30 text-orange-400",
        title: "Amazon Redshift",
        desc: "AWS Redshift database connection",
        icon: "fa-aws",
        img: "/RedShift.svg",
    },
    "Google BigQuery": {
        id: "bigquery",
        color: "bg-cyan-900/30 text-cyan-400",
        title: "Google BigQuery",
        desc: "Google Cloud data warehouse",
        icon: "fa-google",
        img: "/GoogleBigQuery.svg",
    },
    "Azure SQL": {
        id: "azure",
        color: "bg-cyan-900/30 text-cyan-400",
        title: "Azure SQL",
        desc: "Microsoft Azure SQL database",
        icon: "fa-microsoft",
        img: "/Azure.svg",
    },
};
